name: "Display allure result in Summary"
description: "Display allure result in Summary section of workflow"
inputs:
  suites_file:
    required: true
    description: "Path to the allure suites json file. Eg: allure-report/data/suites.json"

runs:
  using: "composite"
  steps:
    - uses: actions/github-script@v7
      env:
        SUITES_FILE: ${{ inputs.suites_file }}
      with:
        script: |
          var tests = [];
          function findTests(obj) {
              if (obj.children) {
                  for (const child of obj.children) {
                      obj = findTests(child);
                  }
              } else {
                  tests.push(obj);
              }
          }

          const fs = require('fs');
          const suites = JSON.parse(fs.readFileSync(process.env.SUITES_FILE, 'utf8'));

          for await (const suite of suites.children) {
              findTests(suite);
              console.log(tests)
              var testTable = [
                [{data: 'Test', header: true}, {data: 'Result', header: true}, {data: 'Parameters', header: true}, {data: 'Duration', header: true}]
              ]

              for (const test of tests) {
                  var s = "Skip ⚪"
                  if(test.status === 'passed') {
                      s = "Pass ✅"
                  } else if (test.status === 'failed') {
                      s = "Fail ❌"
                  }
                testTable.push([test.name, s, JSON.stringify(test.parameters), test.time.duration / 1000 + "s"]);
              }

              await core.summary
                .addHeading(suite.name)
                .addTable(testTable)
                .write()
          }
