name: "Display allure result in Summary"
description: "Display allure result in Summary section of workflow"
inputs:
  path:
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '8'
    - uses: actions/setup-node@v4
      with:
        node-version: 18        
    - shell: bash
      run: |
        npm install -g allure-commandline@2.26.0 --save-dev
        allure generate ${{ inputs.path }}

    - uses: actions/github-script@v7
      with:
        script: |
          var tests = [];
          function findTests(obj) {
              if (obj.children) {
                  for (const child of obj.children) {
                      obj = findTests(child);
                  }
              } else {
                  tests.push(obj);
              }
          }

          const fs = require('fs');
          const suites = JSON.parse(fs.readFileSync('allure-report/data/suites.json', 'utf8'));

          for await (const suite of suites.children) {
              findTests(suite);
              console.log(tests)
              await core.summary
                .addHeading(suite.name)
                .addTable([
                            [{data: 'Test', header: true}, {data: 'Result', header: true}, {data: 'Time', header: true}],
                            ['foo.js' , "Pass ✅", "2"],
                            ['bar.js' , 'Fail ❌', '4'],
                            ['test.js', 'Pass ✅', 200]
                          ])
                .write()
          }
        
