name: "Display allure result in Summary"
description: "Display allure result in Summary section of workflow"
inputs:
  path:
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '8'
    - uses: actions/setup-node@v4
      with:
        node-version: 18        
    - shell: bash
      run: |
        npm install -g allure-commandline@2.26.0 --save-dev
        allure generate ${{ inputs.path }}
        ls -la
    - uses: actions/github-script@v7
      with:
        script: |
          await core.summary
                      .addHeading('Test Results1')
                      .addTable([
                                  [{data: 'Test', header: true}, {data: 'Result', header: true}, {data: 'Time', header: true}],
                                  ['foo.js' , "Pass ✅", "2"],
                                  ['bar.js' , 'Fail ❌', '4'],
                                  ['test.js', 'Pass ✅', 200]
                                ])
                      .write()
      

          await core.summary
              .addHeading('Test Results2 ')
              .addTable([
                          [{data: 'Test', header: true}, {data: 'Result', header: true}, {data: 'Time', header: true}],
                          ['foo.js' , "Pass ✅", "2"],
                          ['bar.js' , 'Fail ❌', '4'],
                          ['test.js', 'Pass ✅', 200]
                        ])
              .write()
        
