name: "Display allure result in Summary"
description: "Display allure result in Summary section of workflow"
inputs:
  path:
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '11'
        
    - shell: bash
      run: |
        wget -q https://github.com/allure-framework/allure2/releases/download/2.26.0/allure_2.26.0-1_all.deb
        sudo dpkg -i allure_2.26.0-1_all.deb
        ls -la
        
