name: "Display allure result in Summary"
description: "Display allure result in Summary section of workflow"
inputs:
  path:
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '8'
    - uses: actions/setup-node@v4
      with:
        node-version: 18        
    - shell: bash
      run: |
        npm install -g allure-commandline@2.26.0 --save-dev
        allure generate ${{ inputs.path }}
    - uses: actions/github-script@v7
      with:
        script: |
          const fs = require('fs')
          const summary = fs.readFileSync(process.env.summaryFile, 'utf8')

          // make the heading array for the core.summary method
          const headingArray = [{data: 'Topic', header: true}, {data: 'Count', header: true}, {data: 'Public', header: true},{data: 'Internal', header: true},{data: 'Private', header: true}]
      
          // convert the summary array into an array that can be passed into the core.summary method
          const summaryArray = JSON.parse(summary).map(t => [t.name, t.count.toString(), t.public.toString(), t.internal.toString(), t.private.toString()])

          // join the two arrays
          const tableArray = [headingArray, ...summaryArray]

          await core.summary
                  .addHeading(`Topics used on repos in the [${process.env.org}] organization`)
                  .addTable(tableArray)
                  .write()
      

        
        
