name: Test

on: push

jobs:
  test:
    runs-on: ubutu-latest
    steps:
      - name: Display allure
        uses: dna-script-inc/allure-report-summary@master
        with:
          path: demo
    
