name: Test

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Display allure
        uses: dna-script-inc/allure-report-summary@master
        with:
          suites_file: ./allure-report/data/suites.json
    
